apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: klikgo
data:
  APP_NAME: "Auth Service"
  APP_VERSION: "1.0.0"
  API_PREFIX: "/api/v1"

  HOST: "0.0.0.0"
  PORT: "8000"

  DATABASE_NAME: "ecommerce_db"

  JWT_ALGORITHM: "HS256"
  JWT_ISSUER: "auth-service"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"