apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: klikgo
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:root123@mongodb:27017/ecommerce_db?authSource=admin"
  JWT_SECRET_KEY: "Satish7"